### ISSUE TITLE
column width setting question

### ISSUE THREAD

**Issue by byunru** [lorenzofox3/Smart-Table#111]
1) is there a way to set column width?
2) is there a way to auto width for columns?

**Comment by serhioV** [comment]
hi. Why the issue was closed? Is there a way to auto-size the colums or not?

I have a button in the last column, say "Edit", in English, "Modifier" en French, "Editar" in Spanish. I need that the colum be AutoSized (automatic width), that is, no free space from the left or right, column width by the content of the largest cell.
