### ISSUE TITLE
Search filter does not support multiple property selection

### ISSUE THREAD

**Issue by dejanberic** [lorenzofox3/Smart-Table#196]
I can not configure search to only search couple of properties from some object.
If object contains key property and that property is not displayed in table, search will search the text in key property also.

**Comment by cyrilchaponeverysens** [comment]
Filtering on every properties, with a virgin `st-search` is pretty much confusing since it even filters on hidden (no shown) properties. One wouldn't want to recode the thing because *filtering on every only-show properties* is, well I guess, the default behavior I want (and I guess am not the one) on my every tables.

This behavior would be ok if one could explicitly define a range of properties but thats not the case. I'd like to implement [something like that](http://stackoverflow.com/a/26011830/4578952) in a generic way that accepts a range of properties. Though, trying to imitate default `$parse` is way over my angular skills. Any help here ?

**Comment by lorenzofox3** [comment]
I am not sure to understand. 
But why not simply removing unwanted(hidden) properties from your dataset so the predicate ``$`` would filter the desired subset 

```Javascript
$scope.rowCollection = data.map(function(item){
   return {
     wantedProperty:item.wantedProperty,
     wantedProperty2:item.wantedProperty2  
  };
});
```

**Comment by cyrilchaponeverysens** [comment]
> why not simply removing unwanted(hidden) properties from your dataset ?

Precisely because they are **hidden** but **not unwanted** at all

Consider this dumb example

```
<tr ng-repeat="thing in displayedThings">
  <td>{{ thing.type === 'somethingspecial ? thing.name.toUpperCase() : thing.name }}</td>
</tr>
```

The other reason could be philosophically one doesn't have to adapt it's or controller collection to the view. What if I use `$scope.things` elsewhere in the view, am I supposed to keep 2 parallel collection ? One would miss the whole point of view-controller relation in my opinion

**Comment by lorenzofox3** [comment]
Then I guess you'll have to write your own filter and use ``st-set-filter``. 
Your problem is not really related to smart table but more 
"how do I use global predicate with default angular filter Filter on a a subset of properties without changing my collection at all ?"

**Comment by cyrilchaponeverysens** [comment]
@lorenzofox3 thanks =)

I hadn't realized that it was relying so much on `filter`.

I'm gonna dig into custom filtering. [this](http://stackoverflow.com/questions/13216115/filtering-by-multiple-specific-model-properties-in-angularjs-in-or-relationship) can help I guess.

**Comment by fvschie** [comment]
I am missing this feature as well.

I have a list of entities with IDs (consisting of UUIDs). I don't display the ID, but do use it in action buttons in the appropriate row. UUIDs can happen to contain words, leading to false positives.

Being able to simply specify st-search="name,description" in some form would make so much sense...
