### ISSUE TITLE
Remove bind for stPipe

### ISSUE THREAD

**Issue by srph** [lorenzofox3/Smart-Table#200]
The `stPipe` directive is causing me issues. In my case, I am using a Base Controller, using `$controller` to be prototypically inheritted. Here's a [plunkr](http://plnkr.co/edit/YqzXGzNqiqMPk1nAiB16?p=preview) for demonstration purposes.

With `this` being binded to the function, this causes me issues: I am unable to access my own controller's `this`. Perhaps a version of `stPipe` without the bind (`st-pipe-no-bind`, ...)?

**Comment by frankmunoz** [comment]
Hi lorenzofox3  and srph, what I need is almost that,  I'm reusing the same table with different data, and I need set in the function of st-pipe attribute a param to let the function knows how work it, something like this
`// js
$scope.myHandler = function(tableState, myParameter) {
  //manipulate here myParameter
}

<table st-table="vm.myCollection" class="table table-hover" st-pipe="vm.myHandler(myParameter)">
`

I hope this be clear because my english is not pretty good!!
Some one knows how can I solve it??

**Comment by frankmunoz** [comment]
Hi lorenzofox3 and srph, what I need is almost that, I'm reusing the same table with different data, and I need set in the function of st-pipe attribute a param to let the function knows how work it, something like this
>// js 
$scope.myHandler = function(tableState, myParameter) {
//manipulate here myParameter
}


> //html
div class="table-responsive" st-table="vm.myCollection" st-pipe="vm.myHandler"


I hope this be clear because my english is not pretty good!!
Some one knows how can I solve it??
