### ISSUE TITLE
Pre-defined sort fields breaking st-sort?

### ISSUE THREAD

**Issue by jaythomas** [lorenzofox3/Smart-Table#267]
Apologies for bringing this to a Github issue when it's in all likelyhood user error, but I couldn't find any examples that used an ng-repeat on table header/column labels.

I'm trying to implement sorting into a re-usable table directive where I feed it a row collection and columns from the row collection to display. When I set st-sort to a static string like "firstName" it works, but setting st-sort to a column label breaks things. It doesn't appear to matter whether it's done in an ng-repeat or not (as I'm assuming the ng-repeat is always first priority in attributes.

http://plnkr.co/edit/Awm65eFCh0XVQB0Pgwdy?p=preview

**Comment by lorenzofox3** [comment]
Hi, 
there are few errors.
1. st-sort expect a key name so you should first bind it to the `field` property rather than the label
2. the collection you have set with `st-table` attribute does not exist (rowCollection -> rows)

Last, you'll have to patch smart-table.
st-sort dirrective is not meant to support binding (except for binding), this can be discussed and I am going to think about it. So in https://github.com/lorenzofox3/Smart-Table/blob/master/src/stSort.js#L23 you'll need to force the evaluation against the scope : it should be
```Javascript
predicate=getter(scope);
```

Have a look at
http://plnkr.co/edit/Elslmn9wnpGY2Nz6ujbp?p=preview

**Comment by jaythomas** [comment]
Thanks for the quick reply. Whoops, the label/field sorting mixup was the result of hastily replicating my table in a plunk...

Anyways, this one line workaround did the trick for me. Hope a fix comes later to properly support binding.
