### ISSUE TITLE
st-search in IE

### ISSUE THREAD

**Issue by shilan** [lorenzofox3/Smart-Table#374]
Due to some weird configuration in IE 9 browser for our whole company, st-search doesn't work properly in our browsers. The problem is when I type some characters in input, it would filter the data but as I clear the input it doesn't refresh and display all the data unless I type a "space" in input.
Well, I just wanted to ask how do you purpose me to change st-search and force it response to backspace or delete button?
Or can you guide me where in smart-table.js do you fire backspace or clearing input event?
I know it is kind of irrelevant, but I really cannot change the whole company browsers, I even cannot find what is this configuration

**Comment by lorenzofox3** [comment]
Maybe you could listen to a different event [here](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stSearch.js#L29)

**Comment by jlflores** [comment]
Sorry I not sure how to link files here but you can replace:

element.bind('input', function (evt) {
          evt = evt.originalEvent || evt;
          if (promise !== null) {
            $timeout.cancel(promise);
          }

          promise = $timeout(function () {
            tableCtrl.search(evt.target.value, attr.stSearch || '');
            promise = null;
          }, throttle);
        });

For:

var filtering = function (evt) {
          evt = evt.originalEvent || evt;
          if (promise !== null) {
            $timeout.cancel(promise);
          }

          promise = $timeout(function () {
            tableCtrl.search(evt.target.value, attr.stSearch || '');
            promise = null;
          }, throttle);
        };
        element.bind('input', filtering);
        element.bind('change', filtering);

That worked for me on Chrome, Firefox and IE

**Comment by shilan** [comment]
Thanks for your replies, I would try that and I would return to you again.

**Comment by shilan** [comment]
looking into this 
http://jsfiddle.net/cCDZ2/
I understood it is IE9 issue. (sorry totally irrelevant issue)
I can convince them to install IE11, and it works there :)

**Comment by dumindaa** [comment]
Seems like the issue is due to IE not firing keypress event for backspace. Fixed by doing below change.
* Added  ng-change="keydown()" attribute to input element
 \<input st-search="name" ng-change="keydown()"/>

* Modified the smart-table 'stSearch' directive to ADD keypress event handler.

   element.on('keydown', function (evt) {
            evt = evt.originalEvent || evt;
            if (promise !== null) {
                $timeout.cancel(promise);
            }
promise = $timeout(function () {
                tableCtrl.search(evt.target.value, attr.stSearch || '');
                promise = null;
            }, throttle);
        });

**Comment by rgsingh** [comment]
@dumindaa I tried this solution for IE9, but it did not work. How is ```keydown()``` implemented?

**Comment by dumindaa** [comment]
Did u modify the smart-table.js and added the key down event in Ng-click event in the html as mentioned in the post?

**Comment by rgsingh** [comment]
Actually, I was referencing smart-table.js via bower in my project and did not rebuild it after modifying the stSearch.js directive. I ended up replacing 'input' with 'keydown' and that seems to work in both Chrome and IE. You can see my change [here](https://github.com/rgsingh/Smart-Table/commit/31b56496e18ba800b7cd2b984f41725820f14208). Not sure if this is the best way, but my thought is since 'keydown' happens prior to 'input', any text input would be picked up. I modified the test specs with this change as well.

**Comment by dumindaa** [comment]
Well It would be good enough if you are like me waiting to see the end of all IE9 installations in the organization soon. Then I don't have to deal with IE9 any more. :-)
