### ISSUE TITLE
Fix header and inifinite scroll

### ISSUE THREAD

**Issue by mgonzalez10** [lorenzofox3/Smart-Table#380]
Hi, 
I need to implement a Infinite-Scroll in the Smart-Table with fixed header.
I tried the infinite-scroll code with many fixed-header directives, but they didn't work.
 How can I do it?.
Thank you.

**Comment by lorenzofox3** [comment]
Hi, 
how do you want me to help ? Just imagine a second you are me and you read this comment. you provide no code, no context, you do not seem to have made any effort. What can I possibly do ?
There are quite few examples on pagination on scroll, some other on fixed headers. Maybe you could try a bit yourself instead of asking me to do your job, don't you think ?
regards,

Laurent

**Comment by mgonzalez10** [comment]
I got it adding a 'fake' header in another table. Then I handle the clic event to fire clic on the smart-table.
I shared in stackoverflow.
