### ISSUE TITLE
Using st-sort with dynamic field name

### ISSUE THREAD

**Issue by yashikagarg13** [lorenzofox3/Smart-Table#381]
How can I use dynamic field name with st-sort. Currently we can just hardcode it

           <table>
                  <thead>
                         <tr>
                           <th ng-repeat="field in fields">{{field}}</th>
                         </tr>
                   </thead>
                   <tbody>
                          <tr ng-repeat="row in data">
                                  <td ng-repeat="item in row">{{item}}</td>
                         </tr>
                   </tbody>
             </table>

               $scope.fields=['id', 'name', 'score'];
               $scope.data = [{'1', 'ABC', '10'}, {'2', 'DEF', '9'}, {'3', 'MNO', '12'}, {'4', 'XYZ', '15'}];

**Comment by lorenzofox3** [comment]
need to interpolate it
```Javascript
<th st-sort="{{field}}"></th>
```

**Comment by yashikagarg13** [comment]
can you suggest code lines for the same or place where I can look to edit for my own version

**Comment by lorenzofox3** [comment]
seriously ? 
```Markup
<table>
              <thead>
                     <tr>
                       <th st-sort="{{field}}" ng-repeat="field in fields">{{field}}</th>
                     </tr>
               </thead>
               <tbody>
                      <tr ng-repeat="row in data">
                              <td ng-repeat="item in row">{{item}}</td>
                     </tr>
               </tbody>
         </table>
```

**Comment by yashikagarg13** [comment]
This doesn't works.. I have tried this already!

**Comment by lorenzofox3** [comment]
Then I don't know. I know that it works fine on the example with draggable headers, so I guess the issue is related to some other part of your code. Maybe if you provide a plunker which reproduces the issue I could help

**Comment by leftiness** [comment]
In my case, `st-sort` caused all of the data in the table to disappear. I tried `{{brackets}}`. I tried no brackets. In the end, the problem was that I was grabbing data with Restangular, but I wasn't using `st-safe-src`. This scenario is explicitly [documented](http://lorenzofox3.github.io/smart-table-website/) (ctrl+f "stSafeSrc attribute"). I just have a bad habit of skipping past the words and them skimming through the code. @yashikagarg13, you might be suffering a similar fate. :)

**Comment by excessum** [comment]
Hello, 

I am also having the same sort of issue, the data structure i am using is a little more complicated than this plunker, but the problem is identical. I have tried to simplify it as much as possible and the issue is that the st-sort on the table will not actually sort the data. 

Is there some error in my code or is it an issue with smart tables?

Plunker : http://plnkr.co/edit/ZC7nE3zxC4SJPtjA0Muf

Thank you in advance

**Comment by lorenzofox3** [comment]
@excessum the problem is in the structure of you data. You ask smart-table to sort your data based on a property ("id","name") which does not exist on your items: 
http://plnkr.co/edit/uEajEc?p=preview.

**Comment by excessum** [comment]
@lorenzofox3 Thanks for the quick reply, I did not realise it needed explicit property names but I will just map it as you have shown.

**Comment by smasithick** [comment]
Hi @lorenzofox3 ,

Here's a new issue with sorting. I'm adding both header and rows dynamically.

Sorting works perfectly.

Here's the scenario, I'm removing a row from the table.

Now, I'm trying to sort. Deleted rows become visible again. It should not and sorting should work with the undeleted rows.

Please let me know the fix.

Here's the plunk [](http://plnkr.co/edit/AnWyzI)
