### ISSUE TITLE
How to set current page

### ISSUE THREAD

**Issue by skidvd** [lorenzofox3/Smart-Table#404]
Hello,

I am presently using stTable with stPagination in the footer.  I have a requirement to dynamically add a new row to the table (I do this by pushing into the st-safe-src array).  This works perfectly, but based upon present sort and filtering settings may NOT be on the current page.  I'm attempting to build a plugin (require ^stTable) that will adjust the current page to show the new row, but so far am not having any success.

I have attempted updating the tableState().pagination.start attribute as well as replacing the entire tableState().pagination object to no avail.  I have a watch set that confirms that my changes are taking affect, but there is not visible reaction on screen.  I've also tried calling stCtrl.slice() and/or stCtrl.pipe() after setting new pagination without success.

How can a dynamically set the page (I note that the pagination directive has a selectPage function, but it is not exposed in a controller)?  Is there a better way to achieve my desired use case (forcing user to page containing newly added row - especially as I am presently on thinking about sort consideration and am not sure how I will yet deal with search values?

TIA!

**Comment by skidvd** [comment]
Update... I have found and resolved the main problem.  As I have, multiple tables on the page, the require ^stTable was not always finding the correct controller for the table in question.  I have reoslved this and now directly setting tableState().pagination.start followed by calling stCtrl.pipe() does effectively change the page number as needed.

I'd still appreciate any thoughts on a better approach to achieve my desired use case (forcing user to page containing newly added row - especially as I am presently on thinking about pagination.sort considerations and am not sure how I will yet deal with pagination.search values.  Also, I what would you think of exposing this sort of 'selectPage' functionality via a controller in the pagination directive?

TIA!

**Comment by lorenzofox3** [comment]
Hi,
the way to go is to use the controller public method [``slice(startIndex, numberOfItem)``](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L137). The selectPage private function of the pagination directive simply calculate the offset index and numbOfItem to provide to ctrl.slice based on the directive configuration.

For the second part of your problem, if you want to locate your new row in the currently "extended" displayed collection, you have the controller public method [getFilteredCollection ](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L151). I say "extended ", because the actual displayed collection only contains the currently displayed page whereas the collection you'll get form getFilteredCollection will return you the result of filter and sort operations based on the current tableState. As the references are the same in every collection, you can do: 
```
ctrl.getFilteredCollection().indexOf(myNewRow)
```
to get the offset to pass to the slice function so that your new item is for example the first item of your page

**Comment by skidvd** [comment]
@lorenzofox3 Thank you for your help and suggestions.  Perhaps I am missing something, but it appears that the getFilteredCollection function will return data based upon present filtering predicate.  In the case that the present filtering predicate would exclude the new (empty) row added, I don't see how this approach will work?

Also from looking at slice, it is essentially a delegate to setting pagination start and number and then calling pipe (as I am already doing in my plugin).  For readability sake, I prefer my present approach as it makes the intent to change the starting point directly obvious.  However, there may be other concerns I am not taking into account.  Do you see a problem with directly setting pagination.start and calling pipe from plugin?

**Comment by lorenzofox3** [comment]
Hi, 
actually I would expect that a new row is inserted accordingly to the current table state, maybe just a matter of opinion. (side note, but I don't see why your new row should be empty)

The reason I suggest `ctrl.slice` rather than setting the table state manually is that one is a public API whereas the other is a (readonly in most of the cases) internal variable. Some could argue it should be private and you should not get access at all ;) 
Indeed, the slice function does not do much, but if you look at other public methods it is not always the case and you'll never know what kind of refactoring the module can have. If you use public methods you should be sure than your code would not break unless there is a new major version (the first digit in semantic versioning). If you use internal variables, it is at your own risk and your code may break even for minor release or bug fixing release.

But if you know what you do, go ahead !

**Comment by skidvd** [comment]
Good point about the public vs private API.  I will use slice for this reason alone.

I need to insert an empty record because the contents are not known at the time of insert and are user configurable thereafter.

**Comment by afgonzal** [comment]
@skidvd I have a similar scenario, do you have an example of how to find your new row when it doesn´t match the current filtering options?

thanks

**Comment by skidvd** [comment]
@afgonzal In my case, I only need to worry about sort ordering of the rows and not filtering.  However, I suspect that the same approach I use to handle ordering could be adapted to handle filtering.  Basically, I just use the smart table controller methods to interrogate the present tableState.  This in combination with knowing something about the 'new' record I inserted (for example knowing that it is either the last or first row in the data set), allows me to determine which page of the data should contain the row.  I then use the stCtrl.slice method to position the table properly to contain the desired page.  The only trick here may be making sure that you are making these checks and position alteration in the subsequent digest cycle (via $timwout or other similar technique), so that the addition of the row in the preceding cycle has had a chance to be rendered.  A final optional step, may be to locate and focus an input in the target new row once the proper page has been sliced.  I do this with traditional angular.element methods to 'find' and focus the proper element.  The below is not pretty, but functional; I'd welcome your thoughts as well for improvement!

`
					scope.data.push({
						id: -((new Date()).getTime()),
						quantity: 0,
						costPerUnit: 0.00,
						totalCost: 0.00
					});

					$timeout(function() {	// need to get to next digest cycle to allow table to be updated first
						// Need to get to correct page in table?
						//console.log('Pages: ' + scope.tableState.pagination.numberOfPages + ' ' + scope.tableState.pagination.number)
						if (scope.tableState.pagination.numberOfPages > 1) {
							if (! scope.tableState.sort.predicate) {
								// table is not sorted, just go to last page
								scope.stCtrl.slice((scope.tableState.pagination.numberOfPages - 1) * scope.tableState.pagination.number, scope.tableState.pagination.number);
							} else {
								if (scope.tableState.sort.predicate === quantityAttribute ||
								 	scope.tableState.sort.predicate === costAttribute ||
									scope.tableState.sort.predicate === extendedAttribute) {
									// these values are defaulted to zero and will be pushed to the first row when reverse is false,
									// so push to first page then, otherwise push to last page
									scope.stCtrl.slice((! scope.tableState.sort.reverse) ? 0 : (scope.tableState.pagination.numberOfPages - 1) * scope.tableState.pagination.number, scope.tableState.pagination.number);
								} else {
									// everything else should be on last page
									scope.stCtrl.slice(scope.tableState.sort.reverse ? 0 : (scope.tableState.pagination.numberOfPages - 1) * scope.tableState.pagination.number, scope.tableState.pagination.number);
								}
							}
						}

						// Focus first element in new row
						$timeout(function() {	// need to get to next digest cycle to allow table to be updated with new page
							var table = element.find('#' + scope.component.name + 'EstimateTable');
							//console.log(scope.component.name + 'EstimateTable ' + table + ' ' + table.length);
							var tbody = table.children('tbody');
							// Row to highlight may be first or last on page depending upon sort order
							var row;
							if (Object.getOwnPropertyNames(scope.tableState.sort).length === 0) {
								// forward search
								row = tbody.children('tr').length - 1;
							} else {
								if (scope.tableState.sort.predicate === quantityAttribute ||
									scope.tableState.sort.predicate === costAttribute ||
									scope.tableState.sort.predicate === extendedAttribute) {
									row = ! scope.tableState.sort.reverse ? 0 : tbody.children('tr').length - 1;
								} else {
									row = ! scope.tableState.sort.reverse ? tbody.children('tr').length - 1 : 0;
								}
							}
							var tr = angular.element(tbody.children('tr')[row]);
							var td = tr.children('td');
							var opener = angular.element(td[1]).children('div'); // first td is delete row icon, so skip to 2nd
							angular.element(opener.find('.fa-toggle-down')).trigger('click');
							scope.editFocus = {
								row: row,
								cell: 0
							}
						}, 0);
					}, 0);
`
