### ISSUE TITLE
using smart tables ajax in the meanjs and mongoose

### ISSUE THREAD

**Issue by Lighiche** [lorenzofox3/Smart-Table#416]
Hey I posed on http://stackoverflow.com/questions/30715587/using-smart-tables-ajax-in-the-meanjs
if you want to take a look there. I'm trying to use this with meanjs. I have this working with dummy data using Angular routes as described in the docs for smart-tables. I get the concept of how smart tables needs to copy my returned ajax data as a separate collection and have made it work in just plain Angular. I'm just not sure where to put it in the mean stack. On the smart-tables site it's written using $http, whereas routing is mainly done in the back end with express and module code is prebuilt for that when you create a CRUD module for the most part. There's a lot more going on in the server.controller file of meanjs. My real issue is that I don't understand which part of the application to modify with the least amount of alteration to the current code.

**Comment by Lighiche** [comment]
So, I'm close to cutting my losses at this point and figuring out some other way to do this, deadlines and all. Although the idea is nice after reading pretty much every preachy and over opinionated piece of documentation this project has to offer and following links to promised clarity that never really pan out. I've come to discover this https://github.com/lorenzofox3/Smart-Table/tree/server-sample.  Yet another short aptly named hardly documented black hole for me to waste my time in. What we have is an over bloated example server that as far as I can see relates to the main branch ... how exactly? I mean sure I could go and read through your 800 line of code commit for all the changes to make to ... what exactly? Seriously seems like any 3rd party module these days likes to tell me just how stupid I am just before I try to use it. And although courtesy isn't a requirement, respect for peoples time should be. Let me bring it back for a sec. Original question? So.. how do I do this shit on the server side? Answer: Completely customize my project. Lelz No. I'd think abut putting that on the tin. Do I hesitate to post this? Well sort of, I don't really any other solution at this point but... then again I've just poured a week into this I can't get back.

**Comment by lorenzofox3** [comment]
Hello, 

I understand you can be frustrated but what can I (or other people) possibly do for you ? You are talking about your server, the ORM you are using and other totally irrelevant blurry things for what ? ... a client side table module. When people downvote (it's not me) your question on stackoverflow, don't you think there is a reason ? You don't provide any code snippet, you don't isolate your problem, you don't show what you have tried or searched. Actually, after reading your Stackoverflow question, I have no idea of what you are talking about  You are basically asking people "Please do my job".
Come on, the branch you are talking about is 2 years old, do you really think it is relevant ? You are talking about wasting people time. Just understand that this project and many open source projects you are using every day are made by people on their free time just because they want to help a community or share their knowledge. Your attitude is the one of someone consuming free stuffs that others have worked on for many hours and then complain because you are to lazy to understand how it works, or because you have quite few things missing in your programming knowledge. If you don't like it, fine.. just build your own module, then build you javascript framework, then build whatever you want. But right now, YOU are the one who waste other people time.

**Comment by Lighiche** [comment]
All good points man, I was under some heavy stress at that point in time, sorry for my 'rant' if you could of heard me say it there would have a lot less snarl behind it. You've done some good work here. But still stand by that fact that out of the entire project yours is the only module I've still never been able to get to play nice, even to this day, and it's not because I'm too lazy to learn how it works, that is a laughable statement based on my core self of which you couldn't possibly know anything beyond the comment I worte, and nothing but a malicious dig on your part, which I fine I was being a bitch anyway.
