### ISSUE TITLE
support for st-search via several fields

### ISSUE THREAD

**Issue by tykayn** [lorenzofox3/Smart-Table#455]
lets say i have a person and i want to filter my smart table via its "name or firstname". for the moment the only way to do this on a single input field is to make it a global search with just the "st-search" attribute, and no value.
it could be a great enhancement to make something to parse with "or", and "and".

example: st-search="name,firstname"

btw, good job for this repo!

**Comment by leofachini** [comment]
Hi @tykayn . You need to code your oun [Angular Filter](https://docs.angularjs.org/api/ng/filter/filter) in order to perform searchings using "OR", "AND" or any custom searches you might see.

Then, you sould set the value of the attribute `<table st-set-filter="yourFilterName" />` in order to Smart Table replace the default global search(global filter) to your custom filter.

I strongly suggest you to take a deep look on those: [#221](https://github.com/lorenzofox3/Smart-Table/pull/221), [#400](https://github.com/lorenzofox3/Smart-Table/issues/400)

:sunglasses:
