### ISSUE TITLE
pagination is not reset while data is updated

### ISSUE THREAD

**Issue by vipintme** [lorenzofox3/Smart-Table#477]
We have using smart table and default pagination functionality. When data is loaded and select a particular page for example five, and smart table data source is updated with new data collection.The page is not reset to first page.It is preserving previous page selection

**Comment by lorenzofox3** [comment]
snippet ? plunker ? (please read the "submit an issue" section on the readme)

**Comment by vipintme** [comment]
This is my plunker solution
http://plnkr.co/edit/8SSoS4lEONbS1p5h1c2v?p=preview

**Comment by mmadden** [comment]
We're also having this issue. Would also be nice if we could retrieve and set the current page.

**Comment by lorenzofox3** [comment]
thanks gonna fix it

**Comment by lorenzofox3** [comment]
http://plnkr.co/edit/wOOHZV?p=preview

**Comment by AdamSelene** [comment]
I think your fix introduced a regression when using pagination with ajax loading, since you're manually setting tableState.pagination.start back to 0 everytime the scope changes. So whenever I update the pagination object after loading the data (i.e. update numberOfPages and totalItemCount), the current page is reset to 0...

**Comment by lorenzofox3** [comment]
I don't think so, the page is set to 0 only when the reference to data source change so
* If you use server side logic (with custom pipe), then nothing change as you don't need safe-src-attribute
* if you use st-safe-src to load asynchronously data reference does not change once you date is loaded
* if you use st-safe-src to add/remove items then reference does not change

what is your usecase ? can you set up a plunker ? Note if you have some weird usecase you can still change the data within the reference collection without change its reference.
```Javascript
source.splice(0,source.length);
source.concat(newbatch);
```

**Comment by AdamSelene** [comment]
Yes I was just working on the plunker (starting from you example in the documentation) and I realized that I was using st-safe-src while loading with Ajax. Without st-safe-src, it works just as expected, my bad :) (the thing is, I was using st-safe-src in the first place, in contradiction with your documentation, because I could not get it to work without it a couple of months ago. I guess I'll never know now :) )
Thanks again for your prompt reply!

**Comment by lorenzofox3** [comment]
:+1:
