### ISSUE TITLE
smart-table with pagination within <form> causes fields to be removed

### ISSUE THREAD

**Issue by jonnysmith1981** [lorenzofox3/Smart-Table#492]
I am using smart-table to display a list of fields that are within a form tag. My smart-table has pagination enabled and pages every 10 items. Currently my table has 13 items in it.

Using AngularJS validation, if I select the 2nd page, change one my fields, the my validation routine fails as the 10 items from the first page have been removed from the $scope.myForm..... object.

How can I get smart-table to not remove elements from the form?

**Comment by lorenzofox3** [comment]
pleas follow the submit an issue guidelines and provide some running example.

**Comment by jonnysmith1981** [comment]
I have just reproduced this bug using a simple variation on examples on the smart-table website. If you see this fiddle: http://jsfiddle.net/jonnyknowsbest/w763L0ts/, it creates 14 random records, and puts them in a smarttable. 

If you make sure the first page is selected and click "Get form elements" the console.table that is produced shows that the form only has 10 elements in it. If you click the second page so the last 4 records are displayed and click "Get form elements", the console.table shows that the form now only has 4 elements in it.

The form should have 14 elements in it regardless of what page is displayed.

**Comment by lorenzofox3** [comment]
> I have just reproduced this bug using a simple variation on examples on the smart-table website
You show my point: it took you 10 minutes, If I have to do it for a 12 of tickets that is already 2hours for me thus the 
"submit an issue" section in the readme ;)

I think what you are experiencing is the expected behaviour for an "efficient" pagination, the rows are removed from the DOM and therefor are not part of the form anymore. 
You can always get access to the whole collection through $scope.rowCollection or event the more relevant [filtered collection](http://stackoverflow.com/questions/31987451/export-only-filtered-data-into-csv-in-angular-smart-table).

If it is not enough for you, then I suggest you implement your own pagination which hide the rows of the previous pages instead of removing them

**Comment by jonnysmith1981** [comment]
I went with the last option. I have used the "pipe" function to set a "hidden" flag on the rows that i dont want displaying, but need to be kept in the form.
