### ISSUE TITLE
Why $timeout improves the performance? Is it a bug with smart-table?

### ISSUE THREAD

**Issue by huynhom** [lorenzofox3/Smart-Table#509]
Take this codes as example: http://plnkr.co/edit/wOOHZV?p=preview

This is the loop I am interested in:
```javascript
      var l = 100;
      for (var j = 0; j < l; j++) {
        $scope.source.push(createRandomItem());
      }
```

Try to increase that to 20000, you will notice it is really slow.
```javascript
      var l = 20000;
      for (var j = 0; j < l; j++) {
        $scope.source.push(createRandomItem());
      }
```
I found that doing it in batches with a $timeout call will largely improve the performance. I tried to put a lot of debug point in smart-table.js but could not have any clue why it is so slow in the beginning? Is it a bug with smart-table where it tries to do something weird in the beginning?
```javascript
      var l = 20000;
      for (var j = 0; j < 10; j++) {
        $scope.source.push(createRandomItem());
      }
      
      $timeout(function() {
        for (var j = 10; j < l; j++) {
          $scope.source.push(createRandomItem());
        }
      }, 1);
```

Thanks

**Comment by lorenzofox3** [comment]
Because browsers run a in a single loop event thread (single thread). So "events" such javascript execution, browser repaint etc are queued. So if you have an expensive blocking loop, the browser won't have the chance to execute other tasks: it has to finish the execution of the current task(running expensive JS). By using timeout you simply tell the browser to queue a new event (the execution of the javascript in the function you pass as first argument) for later which will happen therefore after already queued task (such the next repaint). So what happens basically is that by specifically asking to queue some job for later the browser will: 

1) execute a batch in javascript
2) repaint
3) execute another batch in javascript
4) repaint 

instead of 

1) executing a long time blocking javascript code ...
2) repaint

Note: even if the timeout is set to 0 the task will be queued after already queued other jobs

Have look at the [SO](http://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-sometimes-useful) (the most upvoted answer/solution is not entirely correct though)

**Comment by huynhom** [comment]
Thanks for that lorenzofox3.

But it seems like this blocking is not in that loop.. I tried on my local with same scenario. That JS loop seems to be done very quickly. 

But maybe there are some other big loop in AngularJS ? or maybe I am still missing something here

**Comment by nguillaumin** [comment]
Hi,

Thanks for the explanation, but I'm not sure it completely makes sense here :). In our case we update a large array that takes say 10s. You can run it in one go and it will block the browser for 10s, or you can do 0.1% of it, repaint, then do the 99.9% in another go and it will still block the browser for 9.59s:

I think it's:

```
+--------+
| Render |
+--------+
    |
+---------------+
| block for 10s |
+---------------+
    |
+--------+
| Render |
+--------+
    |
```

versus:

```
+--------+
| Render |
+--------+
    |
+---------------+
| block for 0.1s |
+---------------+
    |
+--------+
| Render |
+--------+
    |
+-----------------+
| block for 9.59s |
+-----------------+
    |
+--------+
| Render |
+--------+
    |
```

You can split the work in two batches, but it takes the same time and will still block the browser. We were in fact able to reproduce that in a simple case without AngularJS (pure JS). Regardless if we put the for loop inside or outside a `setTimeout()` the browser would still get blocked, which I think makes sense.

What we observe here is that updating the large array in a `$timeout()` doesn't block the UI at all anymore, which we have trouble explaining. We've timed the loop when inside and outside the `$timeout` and it takes the same time (~4ms). It seems what is slow is repainting somehow, or something that happens *after* the array has been updated.
* When the loop is outside a timeout, it runs in 4ms but then the UI blocks for 10s
* When the loop is inside a timeout, it still runs in 4ms but then the UI doesn't block

That's what we can't explain, and our concern is that it looks a bit hacky so we're afraid we're missing something here that will cause us grief later.

Possible leads:
* Something to do with Angular scope digesting which would be a lot faster (or happen less frequently?) when inside a timeout?
* Or something to do with rendering, where it behaves differently when it's in a single loop vs. separated in two loops with the big one being inside a timeout.

**Comment by lorenzofox3** [comment]
Then I am not sure to be able to answer your question :). But as a rule of thumb do not put to much nodes (and bindings) or you page. Does a human being can actually read 20 000 rows ? It is better to use a pagination whether on scroll, or with actual pagination control, or other techniques. There is no reason to add on the page nodes that the user is not actually reading

**Comment by nguillaumin** [comment]
Absolutely, I agree with that. That's why we use this library so that only the displayed nodes are on the page, even if we retrieve 4k+ rows from our API backend. What we don't understand I guess is, assuming this library only inject in the DOM the nodes that are needed to be displayed, why is it slow with 4k items?

**Comment by lorenzofox3** [comment]
I don't know :) maybe you have some memory leaks in some part of your code. difficult to say without running example

**Comment by huynhom** [comment]
The issue description actually mention examples and how to get to the problem we are having. You can replicate the issue by changing l to 20000 and then try to use $timeout as mentiones. You can clearly see a performance difference.

**Comment by lorenzofox3** [comment]
mmh, I don't see much difference in the plunker with 20000 rows or 20 rows ?

**Comment by nguillaumin** [comment]
Setting `l` to 20000 definitely makes the UI unresponsive for ~10s for me (on Chrome). Here's perhaps a more immediate example: http://plnkr.co/edit/PhhorIyGHfeDFGEZBix0

You'll see that the page takes ~5s to render, despite the fact that the actual time spent in the loop generating random elements is very small (a few ms).

Increasing `l` increases the time the UI is unresponsive, while not significantly increasing the time spent in the loop. I recommend stopping the plunker, setting a large value like 20,000 or more, and hitting "play". It will take ~10s to render with 20,000 items on my system.

Ah, actually I tried it with Firefox and it was even worse, but because Firefox prompted me about the blocking script a render event was actually processed and I was able to see the intermediary "state" of the table. From what I can tell *all* the rows are rendered first in the page, and then presumably the table gets truncated to the page size. See the screenshot below and observe the huge table and huge scrollbar.

![screenshot](https://cloud.githubusercontent.com/assets/762512/10014354/1561a076-615c-11e5-8beb-a3b9937e4124.png)
