### ISSUE TITLE
Directives are not firing on all pages

### ISSUE THREAD

**Issue by robpolak** [lorenzofox3/Smart-Table#567]
I have a table where each row has a directive.  This directive is responsible for pulling some meta-data and enriching the root object.  It would appear that pages are only rendered when they are selected..  Even directives are not firing on sub-pages.  I am not sure if this is expected behavior.  Is there a way to "force" all pages to render and load directives?

Fiddle:  http://jsfiddle.net/tm3951m1/

Thanks

Rob

**Comment by lorenzofox3** [comment]
yes,
That is the purpose of the pagination: to create dom elements for displayed item only, if the elements not currently displayed had yet dom nodes inserted in the document that would be a poor pagination.

I am afraid you gonna have to think about another strategy. Rolling you own pagination which hide elements instead of removing then could be one
