### ISSUE TITLE
Custom filtering not working after angular 1.3.5?

### ISSUE THREAD

**Issue by ljantzen** [lorenzofox3/Smart-Table#594]
I am currently trying to implement a smart-table that requires sorting and filtering of a table backed by deeply nested objects.  In the process of figuring how st-set-filter works, I noticed that the [plunkr](http://plnkr.co/edit/Idbc1JNHKylHuX6mNwZ6?p=preview) @lorenzofox3 provieded doesn't work with angular 1.3.6 or higher.  As I am currently on angular 1.4.7 this is a showstopper for me.  

Digging in to this issue reveals that the argument values provided to the customComparator have changed, so that  the 'expected' parameter does not contain an object, but just a value.  This might be explained by [this commit](https://github.com/angular/angular.js/commit/f7cf846045b1e2fb39c62e304c61b44d5c805e31#diff-ea6dc49a7f9836eb439e02fd27e86217L156) in the angular source

Is this a known issue, and/or does it have a fix or workaround?

**Comment by lorenzofox3** [comment]
I think if you remove the single quote in st-search for firstname and lastname, the problem is gone

**Comment by ljantzen** [comment]
Unfortunately, no.  [Here](http://plnkr.co/edit/S4DbEHWAvnU1SLcwnbSx?p=preview) is my plnkr.

**Comment by lorenzofox3** [comment]
It is an issue with angular https://github.com/angular/angular.js/issues/11752. 

I don't think you should use a comparator function here just embed your logic within the filter itself

**Comment by ljantzen** [comment]
I dont know if I should use a comparator or not, I am just trying to understand the documetation and examples provided in order to implement before/after filtering on a date in a sub-object property. 

BTW, the strict mode filtering example on the documentation page does not work in Chrome. Filtering on first/last name returns no rows.  Works in Firefox.

**Comment by lorenzofox3** [comment]
Whatever value you set through [search api](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L101), it will be given to the filter used. 

```Javascript
    table.search('whatever',{prop:'foo', other:'bar'})
```

will result in
```
var filter = $filter('your filter or angular filter by default')
filter(array, {whatever:{prop:'foo',other:'bar'}})
```

The problem is that angular filter comparator used not to traverse object if an object value was provided (cf angular issue pointed)
```
function comparator(actual, expected){
 //base logic on  expected = {prop:'foo',other:'bar'} and actual is item.birthDate 

}
```

now it is traversed and result in two calls
```
function (actual,expected){
  // expected = 'foo' and actual is item.birthDate.before (undefined)
}
function(actual,expected){
  // expected = 'bar' and actual is item.birthDate.after (undefined)
}
```
which explain why the code breaks when upgrading angular

On smart-table side nothing has changed and it still work as expected: whatever value you pass to search (object, array, string) it will be forwarded to the filter used. However you have to change the logic of your custom filter to be compliant with new angular filter api and I would rather avoid using a comparator

http://plnkr.co/edit/wDlVgCzIZu0GGg3vGpKf?p=preview

**Comment by ljantzen** [comment]
Ok, thanks. Will try it out.
