### ISSUE TITLE
Natural sorting not working

### ISSUE THREAD

**Issue by emanuelschuetze** [lorenzofox3/Smart-Table#638]
I get a search problem with smart-table 2.1.7:
I sort a column with _st-sort_ (`<th st-sort="name">..</th>`) but I get a wrong (not natural) sort result:

```
Result      Expected
------      --------
foo-1       foo-1
foo-11      foo-2
foo-2       foo-5
foo-25      foo-11
foo-5       foo-25
```

I tested also the documented `st-skip-natural="true"` with same result. So something seems wrong here... Any hints?

**Comment by singhparmjit** [comment]
I believe the sort order in "Result" column is the the right answer in this case, because it is string to string comparison not  number to number.

**Comment by emanuelschuetze** [comment]
If so then smart-table should it not call "natural sort", see https://en.wikipedia.org/wiki/Natural_sort_order. But then the  `st-skip-natural` option makes no sense...

**Comment by emanuelschuetze** [comment]
@lorenzofox3 You closed this issue but I see this not yet resolved. Maybe you can explain what `st-skip-natural` should do and if it should sort "natural". For me it seems that is not working correctly because I get not the expected sort result (see original post in this issue).

**Comment by lorenzofox3** [comment]
Because it is not related to smart-table but rather to angular filter filter. The problem comes from the fact your items are interpreted as strings not numbers and "11" < "2" whereas 2 < 11. 
You can tell smart table to use one of your custom filter rather than angular filter filter if you want. Please read the doc and issues for more details.

### skip-natural
the sort directive can manage 3 states: no sort at all (ie the original order of your collection), sort ascending and sort descending. when you click to a header you go from one state to the other making cycles. People wanted a way to have only two states and skip the default order of the collection, that is what skip-natural is for. Although I admit the name is not the best choice

**Comment by lenichols** [comment]
@lorenzofox3 can you elaborate on how to get the expected result in the original post? Are you saying in the above reply that smart table uses default angular filter? 

* also - if the numbers are converted go NUMBER, would smart table interpret it with decimals?

**Comment by lenichols** [comment]
@emanuelschuetze how did you solve this?

**Comment by emanuelschuetze** [comment]
@lenichols Sorry, we don't use smart table any more...
