### ISSUE TITLE
Please help with rebinding of filters after row collection is updated.

### ISSUE THREAD

**Issue by manojsethi** [lorenzofox3/Smart-Table#665]
I am using latest version of smarttable and using angular js version 1.5

My issue is explained at following link. 

http://stackoverflow.com/questions/36663511/unable-to-refresh-filters-in-header-smart-table

Please help in getting the filters in the table head updated after rowCollection is updated. In mycase only tbody data is updated after ajax call is done but not the table filters.

Please suggest.

**Comment by justiceo** [comment]
I have precisely the same issue.  
After the ajax call and I call $apply(), the data gets updated but the smart-table bindings are not updated and so the filters and search do not work

**Comment by justiceo** [comment]
@manojsethi 
I did a little more looking and discovered the issue has been reported severally in the past and has been closed, because it has been solved.

The solution is to use st-safe-src attribute. According to the documentation on stSafeSrc

> If you are bringing in data asynchronously (from a remote database, restful endpoint, ajax call, etc) you must use the stSafeSrc attribute. You must use a seperate collection for both the base and safe collections or you may end up with an infinite loop.

There is also a good example of st-safe-src on that page. Hope this helps.
This issue is due to be closed

**Comment by manojsethi** [comment]
Issue was that I need to refresh the directive after ajax call. So I placed
the directive link under scope.watch and issue is resolved.
