### ISSUE TITLE
Table goes back to the first page on update when using pagination

### ISSUE THREAD

**Issue by ykyuen** [lorenzofox3/Smart-Table#674]
Thanks for writing this great module!

I have a table which will be updated at a regular interval say 5 seconds. everything works fine except it will go back to the first page when the table data is updated. Any ideas how to keep the current page on data update?

**Comment by vedosity** [comment]
Looks like this was intentional, see issue #477. Should this really be hard-coded behavior? I have a similar use-case where I don't want to be going to the first page on table data update.

**Comment by vedosity** [comment]
Actually, if you don't change the reference to the array, it won't put you back at page 1. So, instead of doing `$scope.array = data;` when your server gives you results, do

    Array.prototype.splice.apply($scope.array, [0, $scope.array.length].concat(data));

to replace the contents of `$scope.array` without changing the array that `$scope.array` references. This will prevent the current page from being set to 0.

**Comment by ykyuen** [comment]
Got it. Thanks. =)
