### ISSUE TITLE
st-set-filter (resrict search) for a single column

### ISSUE THREAD

**Issue by miro94** [lorenzofox3/Smart-Table#685]
Hi

I have  a table with two columns like name and address for example.
For the name field, the search should be a strict-search (exact match), but the address field should not be strict (so I can type in the first letters of the street).

I know the custom filter method to make the whole table search strict:

<table st-set-filter="myFilter" st-table="myData">

`angular.module('myApp').filter('myFilter',
  function($filter) {
    return function(input, predicate) {
      return $filter('filter')(input, predicate, true);
    };
  }
);`

But I can't find a solution to achieve strict search for a single column, for example only for the name.
How can I do this?

Thanks a lot,
Miro

**Comment by beanotj** [comment]
I would like to add to this - it would be nice to have a stStrictSearch that you could apply to the column instead of a global custom filter.

Ex.
`<th>`
`<input st-search="normalSearchProperty" class="input-sm form-control" type="search" />`
`</th>`
`<th>`
`<input st-strict-search="strictSearchProperty" class="input-sm form-control" type="search" />`
`</th>`
