### ISSUE TITLE
Search is triggered when  moving out to another search field : Internet Explorer all versions

### ISSUE THREAD

**Issue by sarvesh43** [lorenzofox3/Smart-Table#687]
smart table default behavior is whenever text is entered in the search field , search is triggered with the st-pipe function
but in internet explorer even on blur or moving out to different text field st-pipe function is getting called

Angular version :  AngularJS v1.3.20
Smart Table Version : @version 2.1.1

**Comment by mihaipanait** [comment]
It seems that in IE, the 'input' event is triggered on input elements that have a placeholder attribute set.
See [this](https://connect.microsoft.com/IE/feedback/details/810538/) or [this](http://www.carsonshold.com/2013/12/js-bug-ie-10-and-11-oninput-event-with-placeholder-set/).

A solution would be to change stConfig.search.inputEvent to 'keypress' instead of 'input'(the default), or simply remove the placeholder attribute from the input element.

related issues:
#712

**Comment by aladd04** [comment]
Do we have a fix for this planned? Or is there a workaround that isn't what mihaipanait suggested? I'm having this issue as well and the "safest" fix seems to be to remove the placeholder all together.
