### ISSUE TITLE
[Info] Date filter plugin

### ISSUE THREAD

**Issue by brazorf** [lorenzofox3/Smart-Table#718]
Hi, i'm searching for a custom date plugin that takes into account localized date formats.
I've found tons of custom made plugins an solutions, as if everyone is coding his own.
Isn't there a released, working one that we can use and assume as a standard?

Thank you.

**Comment by lorenzofox3** [comment]
Totally out of topic

**Comment by brazorf** [comment]
TIL that, on the Smart-table issue queue, a question about a Smart-table plugin is totally out of topic.

If someone out there released this kind of plugin please drop me a line, or we'll just code the 1000th-godziliard clone ourself.

**Comment by lorenzofox3** [comment]
Sorry I was a bit harsh but
1) I don't see how a date filter can be related to a table plugin, this is more specific to angular rather than smart-table
2) And if there are already 999 impl, why not just simply searching for one of them ...
3) As stated this section is for issue/bug report, no open questions. Please use stackoverflow or the chat for that.

Thanks for you contrib and mea culpa
