### ISSUE TITLE
st-pipe not working with st-safe-src

### ISSUE THREAD

**Issue by daniele-bottelli** [lorenzofox3/Smart-Table#727]
Hi there!
I have a problem using smart table using st-safe-src and st-pipe together.
As long as I'm using st-table and st-safe-src directives, I can see all the items in the table.
As long as I'm using st-table and st-pipe directives, I can see all the items in the table.
BUT using st-table, st-safe-src and st-pipe directives, no item is shown in the table.

I tried the solution shown in issue #242 but it didn't work.
In issue #238 joshijimit had my same problem but the solution was: discard st-safe-src. For me it's not possible because I need to filter my table.

You can find my example code here:
http://plnkr.co/edit/NqD47Q?p=preview

Thanks :)

**Comment by MrWook** [comment]
Don't know if you are still in trouble but...
1. update your Angular 
2. dont use st-safe-src with the pipe directive
Without it you can still change data in the table.
Also if you just want to use a filter in the html you dont need st-safe-sr at all. It is used for edit, delete and add a row.
Please look at the pipe example from the main page [http://lorenzofox3.github.io/smart-table-website/](http://lorenzofox3.github.io/smart-table-website/).
There is no st-safe-src

**Comment by daniele-bottelli** [comment]
I found a workaround (I made a directive to add a watch on the table state).

However I do need st-safe-src. This is my usecase:
I have a selectbox filled with the raw collection.
When the user selects an option I have to hide some items accordingly.
It's similar to what you can find here:
https://lorenzofox3.github.io/smart-table-website/#filter-strict-mode

**Comment by AlexNG** [comment]
Have same problem with latest 2.1.8 smart-table. Was quite impossible to work before Angular 1.6, but only since it stopped working (almost) completely. After initial page loading you see empty table until you sort or filter manually. As far I can see, it's because of pipeAfterSafeCopy flag. I guess stPipe was planned for getting data from server and not from in-memory safe-src. We just need "full write access" to this flag.
I have [sample code](https://github.com/AlexNG/Smart-Table/tree/st-pipe_with_safe-src) and [pull request](https://github.com/lorenzofox3/Smart-Table/pull/747)

**Comment by lorenzofox3** [comment]
you are going a bit fast here: your problem have not been reproduced and the build of your pull request is failing. As @MrWook mentionned the pipe function is not meant to be used with st-safe-src as with pipe you have full control on the displayed rows and source rows
