### ISSUE TITLE
Sorting displays the Deleted Rows again

### ISSUE THREAD

**Issue by smasithick** [lorenzofox3/Smart-Table#730]
Hi @lorenzofox3 ,

I'm binding both headers and rows dynamically with different JSON. Sorting works perfectly here.

When I remove a row from the table and try to sort any column, it brings back the deleted rows again. It should not happen.

Here's the plunk [http://plnkr.co/edit/AnWyzI](http://plnkr.co/edit/AnWyzI)

Thanks in advance.

**Comment by lorenzofox3** [comment]
because smart-table create a local copy of your data collection so the array modified is not the same than the one used by the table. You should use the st-safe-src to let the table know to update its copy.

Note: your use case is exactly the same that the second example on the documentation website ...
